name: Cypress Cloud CI/CD

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Installing Dependancies
        uses: cypress-io/github-action@v5
        with:
          runTests: false
      - name: Run and record
        run: npx cypress run --record --key 64e25f46-64b6-468b-8312-31981f1b1317 --browser chrome
